### ISSUE TITLE
EC2 problems finish and pre install state

### ISSUE THREAD

**Issue by cvtt** [cvtt/SEBC#1]
I have many EC2 problems. I forget some settings more times. Ex: disk mount / Securtiy group 

I set and create EC2 tree times. But I solved my problems bow . I will continue.

**Comment by mfernest** [comment]
Can you describe the problem you encountered with security groups and how you fixed it?

**Comment by cvtt** [comment]
My settings was default for the security group. I changed TCP,UDP,ICPM settings.

**Comment by mfernest** [comment]
Thanks

**Comment by cvtt** [comment]
I passed Mysql section. 
I create user that connects to master node, but user password was 'password'. 
My problem : CHANGE MASTER TO MASTER_HOST='master host', MASTER_USER='replica user', MASTER_PASSWORD=**'replica password'**, MASTER_LOG_FILE='master file name', MASTER_LOG_POS=master file offset;

I entered replica password = root password . 

But I created Userpassword = 'password'
I got error : 
/var/log/mysql.log
161115 13:02:00 [ERROR] Slave I/O: error connecting to master 'slave_user@10.234.222.139:3306' - retry-time: 60  retries: 86400, Error_code: 1045

I run : 
[root@r01n01 centos]# service ip6tables stop
[root@r01n01 centos]# chkconfig ip6tables off

My problem was not solved. 

I saw password problem and changed it. 

I passed this steps. 👍

**Comment by mfernest** [comment]
Ahhhh, interesting. I don't believe I saw a review of the CHANGE MASTER parameters in your notes...good catch!
